kind: ConfigMap
metadata:
  name: amf-configmap
  labels:
    app: free5gc
data:
  amfcfg.yaml: |
    info:
      version: 1.0.3
      description: AMF initial local configuration

    configuration:
      serviceNameList:
        - namf-comm
        - namf-evts
        - namf-mt
        - namf-loc
        - namf-oam

      ngapIpList:
        - 10.100.50.249
      sbi:
        scheme: http
        registerIPv4: amf-namf # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: 80
        tls:
          key: config/TLS/amf.key
          pem: config/TLS/amf.pem

      nrfUri: http://nrf-nnrf:8000
      amfName: AMF
      serviceNameList:
        - namf-comm
        - namf-evts
        - namf-mt
        - namf-loc
        - namf-oam
      servedGuamiList:
        - plmnId:
            mcc: 208
            mnc: 93
          amfId: cafe00
      supportTaiList:
        - plmnId:
            mcc: 208
            mnc: 93
          tac: 1
      plmnSupportList:
  